# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(742, 464)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.simulateButton = QtGui.QPushButton(self.centralwidget)
        self.simulateButton.setObjectName(_fromUtf8("simulateButton"))
        self.gridLayout.addWidget(self.simulateButton, 2, 0, 1, 1)
        self.exitButton = QtGui.QPushButton(self.centralwidget)
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.gridLayout.addWidget(self.exitButton, 2, 2, 1, 1)
        self.helpButton = QtGui.QPushButton(self.centralwidget)
        self.helpButton.setObjectName(_fromUtf8("helpButton"))
        self.gridLayout.addWidget(self.helpButton, 2, 1, 1, 1)
        self.simulationProgressBar = QtGui.QProgressBar(self.centralwidget)
        self.simulationProgressBar.setProperty("value", 0)
        self.simulationProgressBar.setObjectName(_fromUtf8("simulationProgressBar"))
        self.gridLayout.addWidget(self.simulationProgressBar, 1, 0, 1, 3)
        self.emitterGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.emitterGroupBox.setObjectName(_fromUtf8("emitterGroupBox"))
        self.emitterRecRadioButton = QtGui.QRadioButton(self.emitterGroupBox)
        self.emitterRecRadioButton.setGeometry(QtCore.QRect(20, 20, 150, 21))
        self.emitterRecRadioButton.setChecked(True)
        self.emitterRecRadioButton.setObjectName(_fromUtf8("emitterRecRadioButton"))
        self.emitterCylRadioButton = QtGui.QRadioButton(self.emitterGroupBox)
        self.emitterCylRadioButton.setEnabled(True)
        self.emitterCylRadioButton.setGeometry(QtCore.QRect(20, 40, 150, 20))
        self.emitterCylRadioButton.setObjectName(_fromUtf8("emitterCylRadioButton"))
        self.emitterElementsGroupBox = QtGui.QGroupBox(self.emitterGroupBox)
        self.emitterElementsGroupBox.setEnabled(True)
        self.emitterElementsGroupBox.setGeometry(QtCore.QRect(10, 260, 220, 91))
        self.emitterElementsGroupBox.setObjectName(_fromUtf8("emitterElementsGroupBox"))
        self.emitterElementsDepthLineEdit = QtGui.QLineEdit(self.emitterElementsGroupBox)
        self.emitterElementsDepthLineEdit.setGeometry(QtCore.QRect(60, 40, 80, 21))
        self.emitterElementsDepthLineEdit.setObjectName(_fromUtf8("emitterElementsDepthLineEdit"))
        self.emitterElementsWidthLabel = QtGui.QLabel(self.emitterElementsGroupBox)
        self.emitterElementsWidthLabel.setGeometry(QtCore.QRect(10, 22, 62, 15))
        self.emitterElementsWidthLabel.setObjectName(_fromUtf8("emitterElementsWidthLabel"))
        self.emitterElementsDepthLabel = QtGui.QLabel(self.emitterElementsGroupBox)
        self.emitterElementsDepthLabel.setGeometry(QtCore.QRect(10, 42, 62, 15))
        self.emitterElementsDepthLabel.setObjectName(_fromUtf8("emitterElementsDepthLabel"))
        self.emitterElementsHeightLabel = QtGui.QLabel(self.emitterElementsGroupBox)
        self.emitterElementsHeightLabel.setGeometry(QtCore.QRect(10, 62, 62, 15))
        self.emitterElementsHeightLabel.setObjectName(_fromUtf8("emitterElementsHeightLabel"))
        self.emitterElementsWidthLineEdit = QtGui.QLineEdit(self.emitterElementsGroupBox)
        self.emitterElementsWidthLineEdit.setGeometry(QtCore.QRect(60, 20, 80, 21))
        self.emitterElementsWidthLineEdit.setObjectName(_fromUtf8("emitterElementsWidthLineEdit"))
        self.label_13 = QtGui.QLabel(self.emitterElementsGroupBox)
        self.label_13.setGeometry(QtCore.QRect(150, 22, 62, 15))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.emitterElementsHeightLineEdit = QtGui.QLineEdit(self.emitterElementsGroupBox)
        self.emitterElementsHeightLineEdit.setGeometry(QtCore.QRect(60, 60, 80, 21))
        self.emitterElementsHeightLineEdit.setObjectName(_fromUtf8("emitterElementsHeightLineEdit"))
        self.label_15 = QtGui.QLabel(self.emitterElementsGroupBox)
        self.label_15.setGeometry(QtCore.QRect(150, 42, 62, 15))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_18 = QtGui.QLabel(self.emitterElementsGroupBox)
        self.label_18.setGeometry(QtCore.QRect(150, 62, 62, 15))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.emitterSizeGroupBox = QtGui.QGroupBox(self.emitterGroupBox)
        self.emitterSizeGroupBox.setEnabled(True)
        self.emitterSizeGroupBox.setGeometry(QtCore.QRect(10, 60, 220, 91))
        self.emitterSizeGroupBox.setAutoFillBackground(False)
        self.emitterSizeGroupBox.setFlat(False)
        self.emitterSizeGroupBox.setCheckable(False)
        self.emitterSizeGroupBox.setObjectName(_fromUtf8("emitterSizeGroupBox"))
        self.emitterWidthMetersLabel = QtGui.QLabel(self.emitterSizeGroupBox)
        self.emitterWidthMetersLabel.setGeometry(QtCore.QRect(150, 22, 62, 15))
        self.emitterWidthMetersLabel.setObjectName(_fromUtf8("emitterWidthMetersLabel"))
        self.emitterWidthLabel = QtGui.QLabel(self.emitterSizeGroupBox)
        self.emitterWidthLabel.setGeometry(QtCore.QRect(10, 22, 62, 15))
        self.emitterWidthLabel.setObjectName(_fromUtf8("emitterWidthLabel"))
        self.emitterHeightMetersLabel = QtGui.QLabel(self.emitterSizeGroupBox)
        self.emitterHeightMetersLabel.setGeometry(QtCore.QRect(150, 62, 62, 15))
        self.emitterHeightMetersLabel.setObjectName(_fromUtf8("emitterHeightMetersLabel"))
        self.emitterHeightLineEdit = QtGui.QLineEdit(self.emitterSizeGroupBox)
        self.emitterHeightLineEdit.setGeometry(QtCore.QRect(60, 60, 80, 21))
        self.emitterHeightLineEdit.setObjectName(_fromUtf8("emitterHeightLineEdit"))
        self.emitterDepthLabel = QtGui.QLabel(self.emitterSizeGroupBox)
        self.emitterDepthLabel.setGeometry(QtCore.QRect(10, 42, 62, 15))
        self.emitterDepthLabel.setObjectName(_fromUtf8("emitterDepthLabel"))
        self.emitterDepthLineEdit = QtGui.QLineEdit(self.emitterSizeGroupBox)
        self.emitterDepthLineEdit.setGeometry(QtCore.QRect(60, 40, 80, 21))
        self.emitterDepthLineEdit.setObjectName(_fromUtf8("emitterDepthLineEdit"))
        self.emitterWidthLineEdit = QtGui.QLineEdit(self.emitterSizeGroupBox)
        self.emitterWidthLineEdit.setGeometry(QtCore.QRect(60, 20, 80, 21))
        self.emitterWidthLineEdit.setObjectName(_fromUtf8("emitterWidthLineEdit"))
        self.emitterHeightLabel = QtGui.QLabel(self.emitterSizeGroupBox)
        self.emitterHeightLabel.setGeometry(QtCore.QRect(10, 62, 62, 15))
        self.emitterHeightLabel.setObjectName(_fromUtf8("emitterHeightLabel"))
        self.emitterDepthMetersLabel = QtGui.QLabel(self.emitterSizeGroupBox)
        self.emitterDepthMetersLabel.setGeometry(QtCore.QRect(150, 42, 62, 15))
        self.emitterDepthMetersLabel.setObjectName(_fromUtf8("emitterDepthMetersLabel"))
        self.emitterPositionGroupBox = QtGui.QGroupBox(self.emitterGroupBox)
        self.emitterPositionGroupBox.setEnabled(True)
        self.emitterPositionGroupBox.setGeometry(QtCore.QRect(10, 160, 220, 91))
        self.emitterPositionGroupBox.setProperty("hidden", False)
        self.emitterPositionGroupBox.setObjectName(_fromUtf8("emitterPositionGroupBox"))
        self.emitterYLineEdit = QtGui.QLineEdit(self.emitterPositionGroupBox)
        self.emitterYLineEdit.setGeometry(QtCore.QRect(60, 40, 80, 21))
        self.emitterYLineEdit.setObjectName(_fromUtf8("emitterYLineEdit"))
        self.emitterXLabel = QtGui.QLabel(self.emitterPositionGroupBox)
        self.emitterXLabel.setGeometry(QtCore.QRect(10, 22, 62, 15))
        self.emitterXLabel.setObjectName(_fromUtf8("emitterXLabel"))
        self.emitterYLabel = QtGui.QLabel(self.emitterPositionGroupBox)
        self.emitterYLabel.setGeometry(QtCore.QRect(10, 42, 62, 15))
        self.emitterYLabel.setObjectName(_fromUtf8("emitterYLabel"))
        self.emitterZLabel = QtGui.QLabel(self.emitterPositionGroupBox)
        self.emitterZLabel.setGeometry(QtCore.QRect(10, 62, 62, 15))
        self.emitterZLabel.setObjectName(_fromUtf8("emitterZLabel"))
        self.emitterXLineEdit = QtGui.QLineEdit(self.emitterPositionGroupBox)
        self.emitterXLineEdit.setGeometry(QtCore.QRect(60, 20, 80, 21))
        self.emitterXLineEdit.setObjectName(_fromUtf8("emitterXLineEdit"))
        self.emitterZLineEdit = QtGui.QLineEdit(self.emitterPositionGroupBox)
        self.emitterZLineEdit.setGeometry(QtCore.QRect(60, 60, 80, 21))
        self.emitterZLineEdit.setObjectName(_fromUtf8("emitterZLineEdit"))
        self.emitterComboBox = QtGui.QComboBox(self.emitterGroupBox)
        self.emitterComboBox.setGeometry(QtCore.QRect(165, 38, 63, 22))
        self.emitterComboBox.setObjectName(_fromUtf8("emitterComboBox"))
        self.emitterComboBox.addItem(_fromUtf8(""))
        self.emitterComboBox.addItem(_fromUtf8(""))
        self.emitterComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.emitterGroupBox, 0, 0, 1, 1)
        self.collectorGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.collectorGroupBox.setObjectName(_fromUtf8("collectorGroupBox"))
        self.collectorCylRadioButton = QtGui.QRadioButton(self.collectorGroupBox)
        self.collectorCylRadioButton.setEnabled(True)
        self.collectorCylRadioButton.setGeometry(QtCore.QRect(20, 40, 150, 20))
        self.collectorCylRadioButton.setObjectName(_fromUtf8("collectorCylRadioButton"))
        self.collectorElementsGroupBox = QtGui.QGroupBox(self.collectorGroupBox)
        self.collectorElementsGroupBox.setGeometry(QtCore.QRect(10, 260, 220, 91))
        self.collectorElementsGroupBox.setObjectName(_fromUtf8("collectorElementsGroupBox"))
        self.collectorElementsDepthLineEdit = QtGui.QLineEdit(self.collectorElementsGroupBox)
        self.collectorElementsDepthLineEdit.setGeometry(QtCore.QRect(60, 40, 80, 21))
        self.collectorElementsDepthLineEdit.setObjectName(_fromUtf8("collectorElementsDepthLineEdit"))
        self.collectorElementsWidthLabel = QtGui.QLabel(self.collectorElementsGroupBox)
        self.collectorElementsWidthLabel.setGeometry(QtCore.QRect(10, 22, 62, 15))
        self.collectorElementsWidthLabel.setObjectName(_fromUtf8("collectorElementsWidthLabel"))
        self.collectorElementsDepthLabel = QtGui.QLabel(self.collectorElementsGroupBox)
        self.collectorElementsDepthLabel.setGeometry(QtCore.QRect(10, 42, 62, 15))
        self.collectorElementsDepthLabel.setObjectName(_fromUtf8("collectorElementsDepthLabel"))
        self.collectorElementsHeightLabel = QtGui.QLabel(self.collectorElementsGroupBox)
        self.collectorElementsHeightLabel.setGeometry(QtCore.QRect(10, 62, 62, 15))
        self.collectorElementsHeightLabel.setObjectName(_fromUtf8("collectorElementsHeightLabel"))
        self.collectorElementsWidthLineEdit = QtGui.QLineEdit(self.collectorElementsGroupBox)
        self.collectorElementsWidthLineEdit.setGeometry(QtCore.QRect(60, 20, 80, 21))
        self.collectorElementsWidthLineEdit.setObjectName(_fromUtf8("collectorElementsWidthLineEdit"))
        self.label_52 = QtGui.QLabel(self.collectorElementsGroupBox)
        self.label_52.setGeometry(QtCore.QRect(150, 22, 62, 15))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.collectorElementsHeightLineEdit = QtGui.QLineEdit(self.collectorElementsGroupBox)
        self.collectorElementsHeightLineEdit.setGeometry(QtCore.QRect(60, 60, 80, 21))
        self.collectorElementsHeightLineEdit.setObjectName(_fromUtf8("collectorElementsHeightLineEdit"))
        self.label_53 = QtGui.QLabel(self.collectorElementsGroupBox)
        self.label_53.setGeometry(QtCore.QRect(150, 42, 62, 15))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_54 = QtGui.QLabel(self.collectorElementsGroupBox)
        self.label_54.setGeometry(QtCore.QRect(150, 62, 62, 15))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.collectorSizeGroupBox = QtGui.QGroupBox(self.collectorGroupBox)
        self.collectorSizeGroupBox.setGeometry(QtCore.QRect(10, 60, 220, 91))
        self.collectorSizeGroupBox.setObjectName(_fromUtf8("collectorSizeGroupBox"))
        self.collectorWidthMetersLabel = QtGui.QLabel(self.collectorSizeGroupBox)
        self.collectorWidthMetersLabel.setGeometry(QtCore.QRect(150, 22, 62, 15))
        self.collectorWidthMetersLabel.setObjectName(_fromUtf8("collectorWidthMetersLabel"))
        self.collectorWidthLabel = QtGui.QLabel(self.collectorSizeGroupBox)
        self.collectorWidthLabel.setGeometry(QtCore.QRect(10, 22, 62, 15))
        self.collectorWidthLabel.setObjectName(_fromUtf8("collectorWidthLabel"))
        self.collectorHeightMetersLabel = QtGui.QLabel(self.collectorSizeGroupBox)
        self.collectorHeightMetersLabel.setGeometry(QtCore.QRect(150, 62, 62, 15))
        self.collectorHeightMetersLabel.setObjectName(_fromUtf8("collectorHeightMetersLabel"))
        self.collectorHeightLineEdit = QtGui.QLineEdit(self.collectorSizeGroupBox)
        self.collectorHeightLineEdit.setGeometry(QtCore.QRect(60, 60, 80, 21))
        self.collectorHeightLineEdit.setObjectName(_fromUtf8("collectorHeightLineEdit"))
        self.collectorDepthLabel = QtGui.QLabel(self.collectorSizeGroupBox)
        self.collectorDepthLabel.setGeometry(QtCore.QRect(10, 42, 62, 15))
        self.collectorDepthLabel.setObjectName(_fromUtf8("collectorDepthLabel"))
        self.collectorDepthLineEdit = QtGui.QLineEdit(self.collectorSizeGroupBox)
        self.collectorDepthLineEdit.setGeometry(QtCore.QRect(60, 40, 80, 21))
        self.collectorDepthLineEdit.setObjectName(_fromUtf8("collectorDepthLineEdit"))
        self.collectorWidthLineEdit = QtGui.QLineEdit(self.collectorSizeGroupBox)
        self.collectorWidthLineEdit.setGeometry(QtCore.QRect(60, 20, 80, 21))
        self.collectorWidthLineEdit.setObjectName(_fromUtf8("collectorWidthLineEdit"))
        self.collectorHeightLabel = QtGui.QLabel(self.collectorSizeGroupBox)
        self.collectorHeightLabel.setGeometry(QtCore.QRect(10, 62, 62, 15))
        self.collectorHeightLabel.setObjectName(_fromUtf8("collectorHeightLabel"))
        self.collectorDepthMetersLabel = QtGui.QLabel(self.collectorSizeGroupBox)
        self.collectorDepthMetersLabel.setGeometry(QtCore.QRect(150, 42, 62, 15))
        self.collectorDepthMetersLabel.setObjectName(_fromUtf8("collectorDepthMetersLabel"))
        self.collectorRecRadioButton = QtGui.QRadioButton(self.collectorGroupBox)
        self.collectorRecRadioButton.setGeometry(QtCore.QRect(20, 20, 150, 21))
        self.collectorRecRadioButton.setChecked(True)
        self.collectorRecRadioButton.setObjectName(_fromUtf8("collectorRecRadioButton"))
        self.collectorPositionGroupBox = QtGui.QGroupBox(self.collectorGroupBox)
        self.collectorPositionGroupBox.setGeometry(QtCore.QRect(10, 160, 220, 91))
        self.collectorPositionGroupBox.setObjectName(_fromUtf8("collectorPositionGroupBox"))
        self.collectorYLineEdit = QtGui.QLineEdit(self.collectorPositionGroupBox)
        self.collectorYLineEdit.setGeometry(QtCore.QRect(60, 40, 80, 21))
        self.collectorYLineEdit.setObjectName(_fromUtf8("collectorYLineEdit"))
        self.collectorXLabel = QtGui.QLabel(self.collectorPositionGroupBox)
        self.collectorXLabel.setGeometry(QtCore.QRect(10, 22, 62, 15))
        self.collectorXLabel.setObjectName(_fromUtf8("collectorXLabel"))
        self.collectorYLabel = QtGui.QLabel(self.collectorPositionGroupBox)
        self.collectorYLabel.setGeometry(QtCore.QRect(10, 42, 62, 15))
        self.collectorYLabel.setObjectName(_fromUtf8("collectorYLabel"))
        self.collectorZLabel = QtGui.QLabel(self.collectorPositionGroupBox)
        self.collectorZLabel.setGeometry(QtCore.QRect(10, 62, 62, 15))
        self.collectorZLabel.setObjectName(_fromUtf8("collectorZLabel"))
        self.collectorXLineEdit = QtGui.QLineEdit(self.collectorPositionGroupBox)
        self.collectorXLineEdit.setGeometry(QtCore.QRect(60, 20, 80, 21))
        self.collectorXLineEdit.setObjectName(_fromUtf8("collectorXLineEdit"))
        self.collectorZLineEdit = QtGui.QLineEdit(self.collectorPositionGroupBox)
        self.collectorZLineEdit.setGeometry(QtCore.QRect(60, 60, 80, 21))
        self.collectorZLineEdit.setObjectName(_fromUtf8("collectorZLineEdit"))
        self.collectorComboBox = QtGui.QComboBox(self.collectorGroupBox)
        self.collectorComboBox.setGeometry(QtCore.QRect(165, 38, 63, 22))
        self.collectorComboBox.setObjectName(_fromUtf8("collectorComboBox"))
        self.collectorComboBox.addItem(_fromUtf8(""))
        self.collectorComboBox.addItem(_fromUtf8(""))
        self.collectorComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.collectorGroupBox, 0, 1, 1, 1)
        self.settingsGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.settingsGroupBox.setObjectName(_fromUtf8("settingsGroupBox"))
        self.threadNumberLineEdit = QtGui.QLineEdit(self.settingsGroupBox)
        self.threadNumberLineEdit.setEnabled(True)
        self.threadNumberLineEdit.setGeometry(QtCore.QRect(150, 20, 71, 21))
        self.threadNumberLineEdit.setObjectName(_fromUtf8("threadNumberLineEdit"))
        self.threadsNumberLabel = QtGui.QLabel(self.settingsGroupBox)
        self.threadsNumberLabel.setGeometry(QtCore.QRect(20, 20, 131, 21))
        self.threadsNumberLabel.setObjectName(_fromUtf8("threadsNumberLabel"))
        self.gridLayout.addWidget(self.settingsGroupBox, 0, 2, 1, 1)
        self.simulationProgressBar.raise_()
        self.emitterGroupBox.raise_()
        self.exitButton.raise_()
        self.helpButton.raise_()
        self.simulateButton.raise_()
        self.collectorGroupBox.raise_()
        self.settingsGroupBox.raise_()
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.emitterRecRadioButton, self.emitterCylRadioButton)
        mainWindow.setTabOrder(self.emitterCylRadioButton, self.emitterWidthLineEdit)
        mainWindow.setTabOrder(self.emitterWidthLineEdit, self.emitterDepthLineEdit)
        mainWindow.setTabOrder(self.emitterDepthLineEdit, self.emitterHeightLineEdit)
        mainWindow.setTabOrder(self.emitterHeightLineEdit, self.emitterXLineEdit)
        mainWindow.setTabOrder(self.emitterXLineEdit, self.emitterYLineEdit)
        mainWindow.setTabOrder(self.emitterYLineEdit, self.emitterZLineEdit)
        mainWindow.setTabOrder(self.emitterZLineEdit, self.emitterElementsWidthLineEdit)
        mainWindow.setTabOrder(self.emitterElementsWidthLineEdit, self.emitterElementsDepthLineEdit)
        mainWindow.setTabOrder(self.emitterElementsDepthLineEdit, self.emitterElementsHeightLineEdit)
        mainWindow.setTabOrder(self.emitterElementsHeightLineEdit, self.collectorRecRadioButton)
        mainWindow.setTabOrder(self.collectorRecRadioButton, self.collectorCylRadioButton)
        mainWindow.setTabOrder(self.collectorCylRadioButton, self.collectorWidthLineEdit)
        mainWindow.setTabOrder(self.collectorWidthLineEdit, self.collectorDepthLineEdit)
        mainWindow.setTabOrder(self.collectorDepthLineEdit, self.collectorHeightLineEdit)
        mainWindow.setTabOrder(self.collectorHeightLineEdit, self.collectorXLineEdit)
        mainWindow.setTabOrder(self.collectorXLineEdit, self.collectorYLineEdit)
        mainWindow.setTabOrder(self.collectorYLineEdit, self.collectorZLineEdit)
        mainWindow.setTabOrder(self.collectorZLineEdit, self.collectorElementsWidthLineEdit)
        mainWindow.setTabOrder(self.collectorElementsWidthLineEdit, self.collectorElementsDepthLineEdit)
        mainWindow.setTabOrder(self.collectorElementsDepthLineEdit, self.collectorElementsHeightLineEdit)
        mainWindow.setTabOrder(self.collectorElementsHeightLineEdit, self.threadNumberLineEdit)
        mainWindow.setTabOrder(self.threadNumberLineEdit, self.simulateButton)
        mainWindow.setTabOrder(self.simulateButton, self.helpButton)
        mainWindow.setTabOrder(self.helpButton, self.exitButton)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Tensor Calculator", None))
        self.simulateButton.setText(_translate("mainWindow", "Simulate", None))
        self.exitButton.setText(_translate("mainWindow", "Exit", None))
        self.helpButton.setText(_translate("mainWindow", "Help", None))
        self.emitterGroupBox.setTitle(_translate("mainWindow", "Emitter", None))
        self.emitterRecRadioButton.setText(_translate("mainWindow", "Rectangular", None))
        self.emitterCylRadioButton.setText(_translate("mainWindow", "Cyllindric", None))
        self.emitterElementsGroupBox.setTitle(_translate("mainWindow", "Elements", None))
        self.emitterElementsDepthLineEdit.setText(_translate("mainWindow", "1", None))
        self.emitterElementsWidthLabel.setText(_translate("mainWindow", "width", None))
        self.emitterElementsDepthLabel.setText(_translate("mainWindow", "depth", None))
        self.emitterElementsHeightLabel.setText(_translate("mainWindow", "height", None))
        self.emitterElementsWidthLineEdit.setText(_translate("mainWindow", "1", None))
        self.label_13.setText(_translate("mainWindow", "elements", None))
        self.emitterElementsHeightLineEdit.setText(_translate("mainWindow", "1", None))
        self.label_15.setText(_translate("mainWindow", "elements", None))
        self.label_18.setText(_translate("mainWindow", "elements", None))
        self.emitterSizeGroupBox.setTitle(_translate("mainWindow", "Size", None))
        self.emitterWidthMetersLabel.setText(_translate("mainWindow", "m", None))
        self.emitterWidthLabel.setText(_translate("mainWindow", "width", None))
        self.emitterHeightMetersLabel.setText(_translate("mainWindow", "m", None))
        self.emitterHeightLineEdit.setText(_translate("mainWindow", "1e-9", None))
        self.emitterDepthLabel.setText(_translate("mainWindow", "depth", None))
        self.emitterDepthLineEdit.setText(_translate("mainWindow", "1e-9", None))
        self.emitterWidthLineEdit.setText(_translate("mainWindow", "1e-9", None))
        self.emitterHeightLabel.setText(_translate("mainWindow", "height", None))
        self.emitterDepthMetersLabel.setText(_translate("mainWindow", "m", None))
        self.emitterPositionGroupBox.setTitle(_translate("mainWindow", "Position", None))
        self.emitterYLineEdit.setText(_translate("mainWindow", "0", None))
        self.emitterXLabel.setText(_translate("mainWindow", "x", None))
        self.emitterYLabel.setText(_translate("mainWindow", "y", None))
        self.emitterZLabel.setText(_translate("mainWindow", "z", None))
        self.emitterXLineEdit.setText(_translate("mainWindow", "0", None))
        self.emitterZLineEdit.setText(_translate("mainWindow", "0", None))
        self.emitterComboBox.setItemText(0, _translate("mainWindow", "xy", None))
        self.emitterComboBox.setItemText(1, _translate("mainWindow", "yz", None))
        self.emitterComboBox.setItemText(2, _translate("mainWindow", "xz", None))
        self.collectorGroupBox.setTitle(_translate("mainWindow", "Receiver", None))
        self.collectorCylRadioButton.setText(_translate("mainWindow", "Cyllindric", None))
        self.collectorElementsGroupBox.setTitle(_translate("mainWindow", "Elements", None))
        self.collectorElementsDepthLineEdit.setText(_translate("mainWindow", "1", None))
        self.collectorElementsWidthLabel.setText(_translate("mainWindow", "width", None))
        self.collectorElementsDepthLabel.setText(_translate("mainWindow", "depth", None))
        self.collectorElementsHeightLabel.setText(_translate("mainWindow", "height", None))
        self.collectorElementsWidthLineEdit.setText(_translate("mainWindow", "1", None))
        self.label_52.setText(_translate("mainWindow", "elements", None))
        self.collectorElementsHeightLineEdit.setText(_translate("mainWindow", "1", None))
        self.label_53.setText(_translate("mainWindow", "elements", None))
        self.label_54.setText(_translate("mainWindow", "elements", None))
        self.collectorSizeGroupBox.setTitle(_translate("mainWindow", "Size", None))
        self.collectorWidthMetersLabel.setText(_translate("mainWindow", "m", None))
        self.collectorWidthLabel.setText(_translate("mainWindow", "width", None))
        self.collectorHeightMetersLabel.setText(_translate("mainWindow", "m", None))
        self.collectorHeightLineEdit.setText(_translate("mainWindow", "1e-9", None))
        self.collectorDepthLabel.setText(_translate("mainWindow", "depth", None))
        self.collectorDepthLineEdit.setText(_translate("mainWindow", "1e-9", None))
        self.collectorWidthLineEdit.setText(_translate("mainWindow", "1e-9", None))
        self.collectorHeightLabel.setText(_translate("mainWindow", "height", None))
        self.collectorDepthMetersLabel.setText(_translate("mainWindow", "m", None))
        self.collectorRecRadioButton.setText(_translate("mainWindow", "Rectangular", None))
        self.collectorPositionGroupBox.setTitle(_translate("mainWindow", "Position", None))
        self.collectorYLineEdit.setText(_translate("mainWindow", "0", None))
        self.collectorXLabel.setText(_translate("mainWindow", "x", None))
        self.collectorYLabel.setText(_translate("mainWindow", "y", None))
        self.collectorZLabel.setText(_translate("mainWindow", "z", None))
        self.collectorXLineEdit.setText(_translate("mainWindow", "0", None))
        self.collectorZLineEdit.setText(_translate("mainWindow", "0", None))
        self.collectorComboBox.setItemText(0, _translate("mainWindow", "xy", None))
        self.collectorComboBox.setItemText(1, _translate("mainWindow", "yz", None))
        self.collectorComboBox.setItemText(2, _translate("mainWindow", "xz", None))
        self.settingsGroupBox.setTitle(_translate("mainWindow", "Settings", None))
        self.threadNumberLineEdit.setText(_translate("mainWindow", "1", None))
        self.threadsNumberLabel.setText(_translate("mainWindow", "How many threads", None))

